GBASEDBTDIR=/opt/gbase8s
GBASEDBTSERVER=ol_gbasedbt1210_1
ONCONFIG=onconfig.ol_gbasedbt1210_1
GBASEDBTSQLHOSTS=$GBASEDBTDIR/etc/sqlhosts.ol_gbasedbt1210_1
GL_USEGLU=1
PATH=$GBASEDBTDIR/bin:$GBASEDBTDIR/extend/krakatoa/jre/bin:$PATH
export GBASEDBTDIR GBASEDBTSERVER ONCONFIG GBASEDBTSQLHOSTS GL_USEGLU PATH
