GBASEDBTDIR=/opt/gbase8s
GBASEDBTSERVER=ol_gbasedbt_1
ONCONFIG=onconfig.ol_gbasedbt_1
GBASEDBTSQLHOSTS=$GBASEDBTDIR/etc/sqlhosts.ol_gbasedbt_1
GL_USEGLU=1
PATH=$GBASEDBTDIR/bin:$GBASEDBTDIR/extend/krakatoa/jre/bin:$PATH
export GBASEDBTDIR GBASEDBTSERVER ONCONFIG GBASEDBTSQLHOSTS GL_USEGLU PATH
