apiVersion: v1
kind: ReplicationController
metadata:
  name: gbase8s-primary
  labels:
    name: gbase8s-primary
spec:
  replicas: 1
  selector:
    name: gbase8s-primary
  template:
    metadata:
      labels:
        name: gbase8s-primary
    spec:
      nodeSelector:
        name: "master"
      containers:
      - name: gbase8s-primary
        image: gbase8s:8.8
        securityContext:
          capabilities:
            add: ["SYS_ADMIN"]
        ports:
        - name: onsoctcp
          containerPort: 9088
        - name: drsoctcp
          containerPort: 19088
        - name: configport
          containerPort: 8000
        env:
        - name: SERVER_TYPE
          value: primary
        - name: GBASEDBT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gbase8s-primary-secret
              key: password
        - name: ONCONFIG_FILE_NAME
          value: /conf/onconfig.ol_gbasedbt_1
        - name: SQLHOSTS_FILE_NAME
          value: /conf/sqlhosts.ol_gbasedbt_1
        - name: DB_LOCALE
          value: zh_cn.utf8
        - name: CLIENT_LOCALE
          value: zh_cn.utf8
        volumeMounts:
        - name: server
          mountPath: /server
        - name: data
          mountPath: /opt/gbase8s/storage
        - name: logs
          mountPath: /opt/gbase8s/logs
        - name: conf
          mountPath: /conf/onconfig.ol_gbasedbt_1
          subPath: onconfig.ol_gbasedbt_1
        - name: conf
          mountPath: /conf/sqlhosts.ol_gbasedbt_1
          subPath: sqlhosts.ol_gbasedbt_1
        - name: conf
          mountPath: /etc/gbasedbt/allowed.surrogates
          subPath: allowed.surrogates
      volumes:
      - name: server
        hostPath:
          path: /root/work/k8s-gbase8s/docker/server
      - name: data
        persistentVolumeClaim:
          claimName: gbase8s-primary-data
      - name: logs
        persistentVolumeClaim:
          claimName: gbase8s-primary-logs
      - name: conf
        configMap:
          name: gbase8s-primary-conf
          items:
            - key: onconfig.ol_gbasedbt_1
              path: onconfig.ol_gbasedbt_1
            - key: sqlhosts.ol_gbasedbt_1
              path: sqlhosts.ol_gbasedbt_1
            - key: allowed.surrogates
              path: allowed.surrogates
---
apiVersion: v1
kind: Service
metadata:
  name: gbase8s-primary
  labels:
    name: gbase8s-primary
spec:
  type: NodePort
  ports:
  - name: onsoctcp
    port: 9088
    targetPort: 9088
    nodePort: 31111
  - name: drsoctcp
    port: 19088
    targetPort: 19088
    nodePort: 31112
  - name: configport
    port: 8000
    targetPort: 8000
    nodePort: 32000
  selector:
    name: gbase8s-primary
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gbase8s-primary-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      name: gbase8s-primary-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gbase8s-primary-logs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      name: gbase8s-primary-logs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gbase8s-primary-data
  labels:
    name: gbase8s-primary-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /gbase/gbase-primary-data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gbase8s-primary-logs
  labels:
    name: gbase8s-primary-logs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /gbase/gbase-primary-logs
