apiVersion: v1
kind: Service
metadata:
  name: gbase8s-cm
  labels:
    app: gbase8s-cm
spec:
  ports:
  - port: 9088
    name: onsoctcp 
  clusterIP: None
  selector:
    app: gbase8s-cm
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gbase8s-cm
spec:
  serviceName: "gbase8s-cm"
  replicas: 1
  selector:
    matchLabels:
      app: gbase8s-cm
  template:
    metadata:
      labels:
        app: gbase8s-cm
    spec:
      containers:
      - name: cm
        image: gbase8s:8.8
        securityContext:
          capabilities:
            add: ["SYS_ADMIN"]
        ports:
        - containerPort: 9088
          name: onsoctcp
