apiVersion: v1
kind: ReplicationController
metadata:
  name: gbase8s
  labels:
    name: gbase8s
spec:
  replicas: 1
  selector:
    name: gbase8s
  template:
    metadata:
      labels:
        name: gbase8s
    spec:
      nodeSelector:
        name: "node1"
      containers:
      - name: gbase8s
        image: gbase8s:8.8
        securityContext:
          capabilities:
            add: ["SYS_ADMIN"]
        ports:
        - name: onsoctcp
          containerPort: 9088
        - name: drsoctcp
          containerPort: 19088
        env:
        - name: GBASEDBT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gbase8s-secret
              key: password
        - name: ONCONFIG_FILE_NAME
          value: /conf/onconfig.ol_gbasedbt_1
        - name: SQLHOSTS_FILE_NAME
          value: /conf/sqlhosts.ol_gbasedbt_1
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        volumeMounts:
        - name: data
          mountPath: /opt/gbase8s/storage
        - name: logs
          mountPath: /opt/gbase8s/logs
        - name: conf
          mountPath: /conf/onconfig.ol_gbasedbt_1
          subPath: onconfig.ol_gbasedbt_1
        - name: conf
          mountPath: /conf/sqlhosts.ol_gbasedbt_1
          subPath: sqlhosts.ol_gbasedbt_1
        - name: conf
          mountPath: /etc/gbasedbt/allowed.surrogates
          subPath: allowed.surrogates
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: gbase8s-data
      - name: logs
        persistentVolumeClaim:
          claimName: gbase8s-logs
      - name: conf
        configMap:
          name: gbase8s-conf
          items:
            - key: onconfig.ol_gbasedbt_1
              path: onconfig.ol_gbasedbt_1
            - key: sqlhosts.ol_gbasedbt_1
              path: sqlhosts.ol_gbasedbt_1
            - key: allowed.surrogates
              path: allowed.surrogates
---
apiVersion: v1
kind: Service
metadata:
  name: gbase8s
  labels:
    name: gbase8s
spec:
  type: NodePort
  ports:
  - name: onsoctcp
    port: 9088
    targetPort: 9088
    nodePort: 31111
  - name: drsoctcp
    port: 19088
    targetPort: 19088
    nodePort: 31112
  selector:
    name: gbase8s
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gbase8s-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      name: gbase8s-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gbase8s-logs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      name: gbase8s-logs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gbase8s-data
  labels:
    name: gbase8s-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /gbase-data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gbase8s-logs
  labels:
    name: gbase8s-logs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /gbase-logs
