GBASEDBTDIR=/opt/gbase8s
GBASEDBTSERVER=ol_generaldata1210
ONCONFIG=onconfig.ol_generaldata1210
GBASEDBTSQLHOSTS=$GBASEDBTDIR/etc/sqlhosts.ol_generaldata1210
GL_USEGLU=1
PATH=$GBASEDBTDIR/bin:$GBASEDBTDIR/extend/krakatoa/jre/bin:$PATH
export GBASEDBTDIR GBASEDBTSERVER ONCONFIG GBASEDBTSQLHOSTS GL_USEGLU PATH
